language: objective-c
osx_image: xcode10

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

before_install:
    - env
    - locale
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - pod --version
    - pod setup
    - pod repo update --silent

script:

    - echo Check if the library described by the podspec can be built
    - pod lib lint --allow-warnings

after_success:
